### ISSUE TITLE
超过10个css文件配置合并后顺序会乱掉？

### ISSUE THREAD

**Issue by hanwsscan** [fex-team/fis-pure#35]
``` javascript
fis.config.set('pack', {
    //合并到main.css
    'css/main.css': [
            'widget/c00.css',
            'widget/c01.css',
            'widget/c02.css',
            'widget/c03.css',
            'widget/c04.css',
            'widget/c05.css',
            'widget/c06.css',
            'widget/c07.css',
            'widget/c08.css',
            'widget/c09.css',
            //'widget/c10.css',
            //'widget/c11.css',
            //'widget/c12.css'
    ]
});
```
#### 10个：按照配置 00 01 02 03 04 05 ....... 09 发布到main.css里

``` css
/*!/widget/c00.css*/
.tab-ctB .tab-ct{border-bottom:1px solid #ebebeb}
/*!/widget/c01.css*/
.tab-ctB .tab-ct{border-bottom:1px solid #ebebeb}
/*!/widget/c02.css*/
.tab-ctB .tab-ct{border-bottom:1px solid #ebebeb}
/*!/widget/c03.css*/
.tab-ctB .tab-ct{border-bottom:1px solid #ebebeb}
/*!/widget/c04.css*/
.tab-ctB .tab-ct{border-bottom:1px solid #ebebeb}
/*!/widget/c05.css*/
.tab-ctB .tab-ct{border-bottom:1px solid #ebebeb}
/*!/widget/c06.css*/
.tab-ctB .tab-ct{border-bottom:1px solid #ebebeb}
/*!/widget/c07.css*/
.tab-ctB .tab-ct{border-bottom:1px solid #ebebeb}
/*!/widget/c08.css*/
.tab-ctB .tab-ct{border-bottom:1px solid #ebebeb}
/*!/widget/c09.css*/
.tab-ctB .tab-ct{border-bottom:1px solid #ebebeb}
```

``` javascript
fis.config.set('pack', {
    //合并到main.css
    'css/main.css': [
            'widget/c00.css',
            'widget/c01.css',
            'widget/c02.css',
            'widget/c03.css',
            'widget/c04.css',
            'widget/c05.css',
            'widget/c06.css',
            'widget/c07.css',
            'widget/c08.css',
            'widget/c09.css',
            'widget/c10.css',
            'widget/c11.css',
            'widget/c12.css'
    ]
});
```

12个：配置从0-12，发布到main.css完全乱掉 

``` css
/*!/widget/c00.css*/
.tab-ctB .tab-ct{border-bottom:1px solid #ebebeb}
/*!/widget/c06.css*/
.tab-ctB .tab-ct{border-bottom:1px solid #ebebeb}
/*!/widget/c02.css*/
.tab-ctB .tab-ct{border-bottom:1px solid #ebebeb}
/*!/widget/c07.css*/
.tab-ctB .tab-ct{border-bottom:1px solid #ebebeb}
/*!/widget/c04.css*/
.tab-ctB .tab-ct{border-bottom:1px solid #ebebeb}
/*!/widget/c05.css*/
.tab-ctB .tab-ct{border-bottom:1px solid #ebebeb}
/*!/widget/c01.css*/
.tab-ctB .tab-ct{border-bottom:1px solid #ebebeb}
/*!/widget/c03.css*/
.tab-ctB .tab-ct{border-bottom:1px solid #ebebeb}
/*!/widget/c08.css*/
.tab-ctB .tab-ct{border-bottom:1px solid #ebebeb}
/*!/widget/c09.css*/
.tab-ctB .tab-ct{border-bottom:1px solid #ebebeb}
/*!/widget/c10.css*/
.tab-ctB .tab-ct{border-bottom:1px solid #ebebeb}
/*!/widget/c11.css*/
.tab-ctB .tab-ct{border-bottom:1px solid #ebebeb}
/*!/widget/c12.css*/
.tab-ctB .tab-ct{border-bottom:1px solid #ebebeb}
```
